### PR TITLE
Header added

### PR DESCRIPTION
**Pull request by 4l3x-suvnet**
Added header block to index.html

### CODE REVIEW

**Comment by Serover** [comment]
Snyggt!

**Comment by Annangggg** [comment]
Niceee

**Review by Serover — APPROVED** [review]
Good

**Review by pollyyllop — APPROVED** [review]
I like it. Very nice design, you work really fast.

**Review by Annangggg — COMMENTED** [review]
nice

**Review by Annangggg — COMMENTED** [review]
hi there

**Pull request merged**
