### PR TITLE
The whole description now shows

### LINKED ISSUE #138: Collapse/expand todo desc
Remove white-space: nowrap; from todo-desc class to show the whole todo description

### PR DESCRIPTION
**Pull request by pollyyllop**
close #138 I removed white-space: nowrap; because it cut the description short. Once removed the whole description now shows.

### CODE REVIEW

**Review by 4l3x-suvnet — CHANGES_REQUESTED** [review]
Description should expand/collapse onclick

**Review by Serover — CHANGES_REQUESTED** [review]
What alex said, I think somewhere in RenderTodo you wanna look into adding Eventlistener to toggle the white-space: nowrap

**Comment by 4l3x-suvnet** [comment]
Clicking the description text now expands/collapses the text correctly. Do we want a button instead, perhaps? I figure it'd be easier for the user to spot.

**Review by Serover — APPROVED** [review]
I made changes and I approve of them

**Review by 4l3x-suvnet — APPROVED** [review]
Looks much better!

**Comment by pollyyllop** [comment]
Hello big-brains. Can we now accept this merge request?

**Review by Annangggg — APPROVED** [review]

**Pull request merged**
